[package]
name = "rusterf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
librp-sys = {path = "librp-sys"}
zmq = "0.10"
serde = {version = "1.0", features = ["derive"]}
toml = "0.4"
gethostname = "0.4"
